### ISSUE TITLE
Tutorials to be made

### ISSUE THREAD

**Issue by Stortebecker** [Stortebecker/training-material#3]
Here I present a list of techniques, which I think should be covered by our proteomics tutorials. The list will be incomplete and so far not ordered after priorities. Any help and comments are appreciated! I included a column "user level" (basic / expert) to mark how much proteomic data experience is expected from users (or how deep the knowlegde will hopefully be after the tutorial). I would like to include some basic information about how to find the right parameters and basic QC in each tutorial and additional expert level tutorials on those topics. Also, methods to visualize should be included in basic tutorials as far as possible. The tutorials below are all meant for users, not admins or developers. In time, a second list of tutorials for the latter groups could be made.

Topic | Content | User Level | Status
:-- | :--: | :--: | :--:
Database Handling | Uploading and merging databases; decoy databases; contaminant databases. | Basic | Completed
Peptide and Protein ID (using SG / PS) | Preparing raw data; peptide-to-spectrum matching; Peptide and Protein ID using SearchGUI and Peptide Shaker; short comment on evaluation of results | Basic | Completed
Peptide and Protein ID (using OpenMS tools) | analogue to the above; OpenMS tools allow for some more settings for expert users | Expert | Not started
Peptide and Protein Quantitation via SIL (using OpenMS tools) | Quantitation based on stable isotope labelling (SIL): Importing and Converting Peptide and Protein IDs; MS1 Feature Detection; Quant to ID matching | Basic | Work in progress
Peptide and Protein Quantitation via isobaric tags |  Quantitation based on isobaric tags (TMT / iTRAQ) | Basic | Not started
Peptide and Protein Quantitation (labelfree) | Introduction to different methods (Spectral counting etc.); detailed description of the method-of-choice (yet to define); alignment of MS runs | Basic | Not started
Swath data analysis | To be defined | Basic | Not started
MRM data analysis | To be defined; maybe include also other targeted approaches? | Basic | Not started
Quality control (maybe split up for each type of experiment) | Automated and manual QC of raw data (machine errors) and data analysis (bad settings); How to know if my results are good or bad?; Common caveats | Expert | Not started
Proteomics Data Visualisation | Summary of different data types and possible visualizations | Basic / Expert | Not started
Statistical analysis of quantitative proteomics data I | Discuss methods: t-test, DE-Seq, Limma, more?; explain methods-of-choice (yet to define) in detail | Basic / Expert | Not started
Statistical analysis of quantitative proteomics data II | Principal component analysis, what else? | Basic | Not started 
Functional analysis of results (maybe split up) | Go term handling (annotation, enrichment, interpretation); localization prediction; what else? | Basic | Not started

That's it for a start. You can find the completed tutorials [here](https://github.com/Stortebecker/training-material/tree/master/Proteomics) and the work in progress [here](https://github.com/Stortebecker/training-material/tree/new_material/Proteomics). A last comment: Proteomic users are pretty ingenious in finding new types of experiments. Here, I tried to focus on the most commonly used methods only. If you think another technique should be included or one of the above methods is not appropriate, please comment.

Thanks for the help!

**Comment by bgruening** [comment]
@Stortebecker you should work more on the main repo. This is very useful for others as well and should be very prominently discussed at the main repo.

**Comment by Stortebecker** [comment]
This issues has been duplicated, please add future comments [here](https://github.com/galaxyproject/training-material/issues/237).
