### ISSUE TITLE
OpenMS tool issues

### ISSUE THREAD

**Issue by Stortebecker** [Stortebecker/training-material#6]
As there are still so many bugs in OMS tools, I wanted to post them separately, not in issues dedicated to a tutorial / workflow.

**Comment by Stortebecker** [comment]
Here comes the first one: FileConverter crashes after clicking `Execute`. No job is added to the history.
@bgruening @blankclemens

```
The server could not complete the request. Please contact the Galaxy Team if this error persists.

{
    "tool_id": "FileConverter",
    "tool_version": "2.1.0",
    "inputs": {
        "param_in": {
            "values": [
                {
                    "src": "hda",
                    "keep": false,
                    "hid": 51,
                    "id": "7844580fc920c668",
                    "name": "FeatureFinderMultiplex on data 49"
                },
                {
                    "src": "hda",
                    "keep": false,
                    "hid": 54,
                    "id": "f95854ffa292747b",
                    "name": "FeatureFinderMultiplex on data 47"
                },
                {
                    "src": "hda",
                    "keep": false,
                    "hid": 57,
                    "id": "4ce70fedb5ee27bb",
                    "name": "FeatureFinderMultiplex on data 48"
                }
            ],
            "batch": true
        },
        "param_UID_postprocessing": "ensure",
        "param_out_type": "csv",
        "param_write_mzML_index": "false",
        "adv_opts|adv_opts_selector": "advanced",
        "adv_opts|param_TIC_DTA2D": "false",
        "adv_opts|param_MGF_compact": "false",
        "adv_opts|param_process_lowmemory": "false",
        "adv_opts|param_force": "false"
    }
}
```

**Comment by Stortebecker** [comment]
Ah, it is a problem with multiple file input: when running only one file, the error is as usual: 

```
Warning: Cannot create folder '.OpenMS' in user home directory. Please check your environment!
         Home directory determined is: /usr/local/galaxy.

```

**Comment by Stortebecker** [comment]
Ach ja, beim `FeatureFinderMultiplex` könnte man tickboxen für optionalen Output hinzufügen, ähnlich wie bei PS. Er macht jetzt standardmäßig drei outputs: consensusXML, featureXML, mgf. Man braucht sicher selten alle drei.

**Comment by Stortebecker** [comment]
`IDFileConverter` kann keine mzid files in idXML umschreiben. Error: 
    Warning: Could not determine format of input file '/data/1/galaxy_db/files/003/823/dataset_3823757.dat'!
     Progress of 'Loading...':
     Error: Unknown input file type given. Aborting!

**Comment by Stortebecker** [comment]
@blankclemens  `TextExporter` creates four tabular output files, only the first contains data, the other are empty.

**Comment by Stortebecker** [comment]
Bei `FileConverter` v.2.2.0 ist der Wrapper defekt, man kann nix einstellen, v.a. nicht den Output File Type. Deshalb crasht das Tool.

**Comment by blankclemens** [comment]
Regarding the `TextExporter`: The output files will contain data if the input is a `consensusXML`. Sadly, out of the tool information it is not possible to tell automatically when these outputs are needed - I'll check if we can fix this, otherwise I might do a manual fix. For the time being, let's enjoy these empty files!

**Comment by blankclemens** [comment]
`FileConverter`: It works just fine for me, for some reason all settings are hidden in the advanced options. Kek.

**Comment by Stortebecker** [comment]
`FileConverter`: Jep, sorry. It works now, but I had to modify the old workflow I used...

**Comment by blankclemens** [comment]
Oh, did it change?

Edit: Yes indeed, all the options where made advanced in OpenMS 2.2.

**Comment by Stortebecker** [comment]
yep, in v 2.1.0, this option was not hidden in the Advanced section
