### ISSUE TITLE
GitHub Pages display issues

### ISSUE THREAD

**Issue by Stortebecker** [Stortebecker/training-material#7]
Ich kapiere nicht, warum die metadaten auf https://galaxyproject.github.io/training-material//Proteomics/tutorials/database-handling nicht angezeigt werden. In https://github.com/galaxyproject/training-material/blob/master/metadata/Proteomics.yml sind sie jedenfalls eingetragen.
Wo ist der fehler?

**Comment by Stortebecker** [comment]
Ok, this was fixed. 

There is a new problem: in the tutorial "labelfree_vs_labelled" the "time estimation" is still not displayed, although it is mentioned in the "Proteomics.yml". The format is exactly the same as for the my other tutorials and there the time estimation is displayed. I cannot find the error. @blankclemens: Can you help?

**Comment by blankclemens** [comment]
That's because there it's written `time estimation: "15min"`, missing the underscore. Fixed it in galaxyproject.

**Comment by Stortebecker** [comment]
thanks! but why did it work in the other material?

**Comment by blankclemens** [comment]
Because there you didn't have this typo? ;-)
